name: build container image
on:
  workflow_dispatch
#   push:
#     branches: 
#     - main
jobs: 
  scale-up: 
    runs-on: [self-hosted, base, dev]
    steps:
    - name: Scale deployment
      run: | 
        kubectl scale deployment dotnet7-runner --replicas 3
        kubectl scale deployment buildah-runner --replicas 3
  
  build:
    needs: [scale-up]
    runs-on: [self-hosted, dotnet7, dev]
    outputs: 
      version: ${{env.date}}
    steps:
    - name: Set The Image Tag
      id: date
      run: echo "date=$(date +'%Y-%m.%d.%H%M')" >> $GITHUB_ENV
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build image using buildah
      run: | 
        buildah bud -f /home/runner/_work/dotnet7-sample/dotnet7-sample/App/Dockerfile --format docker --tls-verify=false -t quay.io/andygodish/dotnet7-sample:${{ env.date }}


  push:
    needs: [build]
    runs-on: [self-hosted, buildah, dev]
    steps: 
    - name: Push image
      run: | 
        buildah login -u="andygodish+dotnet7sample" -p=${{ secrets.QUAY_PASSWORD }} quay.io
        buildah push quay.io/andygodish/dotnet7sample:${{ needs.build.outputs.version }}

  scale-down: 
    needs: [scale-up]
    runs-on: [self-hosted, base, dev]
    steps:
    - name: Scale deployment
      run: | 
        kubectl scale deployment dotnet7-runner --replicas 0
        kubectl scale deployment buildah-runner --replicas 0
  
